import Head from "next/head";

import LoginInput from "@molecules/loginInput";

import styles from "./styles.module.css";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={styles.main}>
        <EmailInput />
        <PasswordInput />
      </main>
    </>
  );
};
const EmailInput = () => {
  return (
    <>
      <LoginInput
        iconPrefix="fas"
        iconName="user"
        placeholder="E-Mail"
      />
    </>
  );
};
const PasswordInput = () => {
  return (
    <>
      <LoginInput
        iconPrefix="fas"
        iconName="lock"
        placeholder="Password"
      />
    </>
  );
};

export default Home;
