import Head from "next/head";

import LoginForm from "@organisms/loginForm";
import PasswordResetMailSentModal from "@organisms/passwordResetMailSentModal";

import { useLogin } from "./hooks";
import styles from "./styles.module.css";

import Modal from "src/components/templates/modal";

const Login = () => {
  const { isModalOpen } = useLogin();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={styles.main}>
        <LoginForm />
        <Modal isOpen={isModalOpen}>
          <PasswordResetMailSentModal />
        </Modal>
      </main>
    </>
  );
};

export default Login;
