import Head from "next/head";

import LoginForm from "@organisms/loginForm";

import styles from "./styles.module.css";

const Login = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={styles.main}>
        <LoginForm />
      </main>
    </>
  );
};

export default Login;
